"""empty message

Revision ID: 7867a504e951
Revises: af0527b75006
Create Date: 2021-02-04 18:37:05.900048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7867a504e951'
down_revision = 'af0527b75006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_date', sa.DateTime(), nullable=True))
    op.drop_column('post', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.drop_column('post', 'post_date')
    # ### end Alembic commands ###
