"""empty message

Revision ID: af0527b75006
Revises: 
Create Date: 2021-02-04 18:35:17.704680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af0527b75006'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'date')
    # ### end Alembic commands ###
